### ISSUE TITLE
Magic Bug

### ISSUE THREAD

**Issue by FakelsHub** [FakelsHub/sFall-Extended#21]
```
procedure start;
procedure magic;

procedure start begin
   variable LVar0 := magic();
   if (game_loaded) then begin

   end
end
procedure magic begin
   display_msg("magic test");
end
```

**Comment by NovaRain** [comment]
I just got a "magic test" message after loading/starting a game. What's the supposed (or bugged) result?

**Comment by FakelsHub** [comment]
I have not yet searched for the reason for calling the procedure.

**Comment by NovaRain** [comment]
I think it's the engine wants to get a value for LVar0, so it calls `magic` procedure trying to get something, and of course it got nothing (LVar0 is probably 0) after calling magic procedure.

**Comment by FakelsHub** [comment]
hah,  sure.
